services:
  - type: web
    name: scheme-saathi-backend
    plan: free
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
